# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install: 
- brew update
- brew upgrade xctool
- gem update cocoapods
- cd Example && pod install && cd -
script:
- xctool clean build test -workspace Example/SHMKit.xcworkspace -scheme Tests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
