# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
# before_install: cd Example && pod install && cd -
script:
- brew update
- brew upgrade xctool
- gem update cocoapods
- cd Example && pod install && cd -
- xctool test -workspace Example/SHMKit.xcworkspace -scheme SHMKit-Tests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
