# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install: 
- gem install cocoapods
script:
- set -o pipefail && xcodebuild test -workspace Example/SHMKit.xcworkspace -scheme SHMKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
