language: objective-c
xcode_project: SHMKit.xcodeproj
xcode_scheme: SHMKit
xcode_sdk: iphonesimulator8.0
script:
  - brew update
  - xctool -project SHMKit.xcodeproj -scheme SHMKit -sdk iphonesimulator build test
